services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    env_file: 
      .env
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
    ports:
      - 19972:1972
      - 59773:52773
      - 8080:8080
    volumes:
      - ./:/home/irisowner/dev

  webapp:
    build:
      context: webapp
      dockerfile: ./webapp/Dockerfile.webapp
    container_name: webapp
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - iris